/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.Mung;

import me.Mung.listener.CommandManager;
import me.Mung.listener.EventListener;
import me.Mung.listener.MessageListener;
import me.Mung.listener.SlashCommandManager;
import me.Mung.util.WalkScheduler;
import net.dv8tion.jda.api.JDA;
import net.dv8tion.jda.api.JDABuilder;
import net.dv8tion.jda.api.OnlineStatus;
import net.dv8tion.jda.api.entities.Activity;

import javax.security.auth.login.LoginException;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

public class Bot {
    public static CommandManager cmdMan;
    public static SlashCommandManager slashCmdMan;
    public static JDA jda;


    //기본 생성자를 통해 봇 활성화
    public Bot() throws LoginException {
        JDABuilder builder = JDABuilder
                .createDefault(Config.get("TOKEN"));

        builder.addEventListeners(new EventListener());
        builder.addEventListeners(new MessageListener());
        builder.setActivity(Activity.playing("숙제 관리"));
        builder.setStatus(OnlineStatus.ONLINE);
        jda = builder.build();
        cmdMan = new CommandManager();
        jda.addEventListener(slashCmdMan = new SlashCommandManager());
        consoleListener();
        activitySwitcher();
    }

    private void activitySwitcher() {
        new WalkScheduler().resetHomework(06, 00, 00);
        new WalkScheduler().walking(06, 00, 00);

    }

    private void consoleListener() {
        new Thread(() -> {
            String line = "";
            BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
            try {
                while ((line = reader.readLine()) != null) {
                    if (line.equalsIgnoreCase("exit")
                            && jda != null) {
                        for (int i = 3; i > 0; i--) {
                            System.out.printf("Stop in %d sec\n", i);
                            Thread.sleep(1000);
                        }
                        jda.getPresence().setStatus(OnlineStatus.OFFLINE);
                        jda.shutdown();
                        System.exit(0);
                    }
                }

            } catch (IOException | InterruptedException e) {
                e.printStackTrace();
            }
        }).start();
    }

    public static CommandManager getCmdMan() {
        return cmdMan;
    }


    public static void main(String[] args) throws LoginException {
        new Bot();
    }
}
