/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.Mung;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import javax.security.auth.login.LoginException;

public class BotTest {

    @Test
    public void testAppHasAGreeting() throws LoginException {
        Bot classUnderTest = new Bot();

        Assertions.assertNotNull(classUnderTest);//"app should have a greeting",

    }
}
